# Generated by Django 3.2 on 2023-06-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230611_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_favorite',
            new_name='is_favorited',
        ),
    ]
